sudo: required
services:
  - docker

before_install:
  - docker build -t antchi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antchi/react-test npm test

after_success:
  - docker build -t antchi/multi-client ./client
  - docker build -t antchi/multi-server ./server
  - docker build -t antchi/multi-nginx ./nginx
  - docker build -t antchi/multi-worker ./worker
  # Log in to the docker CLI, command sends the password as argument to second command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push antchi/multi-client
  - docker push antchi/multi-server
  - docker push antchi/multi-nginx
  - docker push antchi/multi-worker